export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const COLLECTION_ROUTE = '/collection'
export const MAIN_ROUTE = '/picturebin'
export const PICTURE_ROUTE = '/picture'